version: '3'
services:
  app:
    build: ./back-end
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./back-end:/app
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
  front:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    working_dir: /app
    command: npm run start
    depends_on:
      - app
